### ISSUE TITLE
bug(khnormal): coeng identification treats any number of bases immediately following coeng+base as a coeng as well

### ISSUE THREAD

**Issue by mcdurdin** [sillsdev/khmer-character-specification#12]
https://github.com/sillsdev/khmer-character-specification/blob/ed903dd4dc03de355579056f2ec4a8e6dc83dca0/python/scripts/khnormal#L91-L94

This loop propagates the coeng category incorrectly -- because the base following coeng has just been reclassified as coeng as well.

For example: \u1781\u17c2\u17d2\u1798\u179a (ខែ្មរ) produces \u1781\u17d2\u1798\u179a\u17c2 (ខ្មរែ) instead of \u1781\u17d2\u1798\u17c2\u179a (ខ្មែរ)

**Comment by mcdurdin** [comment]
Perhaps:

```
        if txt[i-1] == "\u17D2" and charcats[i] in (Cats.Base, Cats.ZFCoeng):
```

@mhosken

**Comment by mhosken** [comment]
Ouch. Yes.

**Comment by mcdurdin** [comment]
Fixed by https://github.com/sillsdev/khmer-character-specification/commit/147f7392471f569901b52ea5583eddac2785eddb
